---
cloud_user: ''

# renovate: datasource=github-releases depName=fluxcd/flux2 versioning=semver
flux_cli_ver: "2.7.3"

flux_cli_install_dir: /usr/local/bin

flux_cli_force_update: false

#https://github.com/fluxcd/flux2/releases/tag/v2.7.1
#https://github.com/fluxcd/flux2/releases/download/v2.7.1/flux_2.7.1_linux_amd64.tar.gz
flux_cli_download_url: 'https://github.com/fluxcd/flux2/releases/download/v{{ flux_cli_ver }}/flux_{{ flux_cli_ver }}_linux_amd64.tar.gz'

#https://github.com/fluxcd/flux2/releases/download/v2.7.1/flux_2.7.1_checksums.txt
# renovate: datasource=github-releases depName=fluxcd/flux2 packageName=flux_<semver>_linux_amd64.tar.gz
flux_cli_checksum: "sha256:dbd088c133aee74c409d51fb26d2b3ba3727ca304b88ecc0bf6af878bec007d3" # Actual checksum
