---
#Must be the same version as the gitlab-ee server
# https://gitlab.com/gitlab-org/gitlab-runner/-/releases
# https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/index.html

#Gitlab Runner packages: https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/index.html
##wget https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/binaries/gitlab-runner-linux-amd64
##wget https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/binaries/gitlab-runner-helper/gitlab-runner-helper.x86_64

evocode_runner_version: 18.6.0

evocode_runner_url: 'https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/v18.6.0/binaries/gitlab-runner-linux-amd64'

evocode_runner_checksum: sha256:cd6f470fd3f84f78eac2e7576fca0b2c14fc91a39b3dcecda8f43c55bd549640

evocode_runner_helper_url: 'https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/v18.6.0/binaries/gitlab-runner-helper/gitlab-runner-helper.x86_64'

evocode_runner_helper_checksum: sha256:21d280aeec05265403c98b2e3f80c4be67c973636ea08ead644687fa9361dc36

evocode_runner_force_update: false

evocode_runner_install_dir: '/usr/local/bin'

evocode_runner_ci_user: 'gitlab-runner'