---
#--------------------------------------------------------------
# COSIGN SPECIFIC VARS
#--------------------------------------------------------------
# Cosign Version
# renovate: datasource=github-releases depName=sigstore/cosign versioning=semver
cosign_version: "v3.0.2"

# Directory
cosign_dir: "/opt/cosign"

# Packages
cosign_binary: "cosign-linux-amd64"

# URLS
cosign_github_url: "https://github.com/sigstore/cosign/releases/download/{{ cosign_version }}"

#https://github.com/sigstore/cosign/releases/
# renovate: datasource=github-releases depName=sigstore/cosign packageName=cosign-linux-amd64
cosign_checksum: sha256:46dbdcb5467a3dfec2526923d0b3365e40c8d9dc00ec23d5aca3437449e8cbfd
