---
cloud_user: ''

# renovate: datasource=github-releases depName=go-task/task versioning=semver
task_ver: 'v3.46.4'

task_install_dir: /usr/local/bin

task_force_update: false

#https://github.com/go-task/task/releases/tag/v3.46.4
#https://github.com/go-task/task/releases/download/v3.46.4/task_linux_amd64.tar.gz
task_download_url: 'https://github.com/go-task/task/releases/download/{{ task_ver }}/task_linux_amd64.tar.gz'

#Manually computed
# renovate: datasource=github-releases depName=go-task/task packageName=task_linux_amd64.tar.gz
task_checksum: sha256:4b0098862292de03d568c851b207bce5fdb8a59cb533d6ed4132386151926c46
