---
cloud_user: ''

# renovate: datasource=github-releases depName=go-task/task versioning=semver
task_ver: 'v3.45.5'

task_install_dir: /usr/local/bin

task_force_update: false

#https://github.com/go-task/task/releases/tag/v3.45.5
#https://github.com/go-task/task/releases/download/v3.45.5/task_linux_amd64.tar.gz
task_download_url: 'https://github.com/go-task/task/releases/download/{{ task_ver }}/task_linux_amd64.tar.gz'

#Manually computed
# renovate: datasource=github-releases depName=go-task/task packageName=task_linux_amd64.tar.gz
task_checksum: sha256:e547ea2a47f5240657fdc89ea776baa90d628a1f2748242eaa7478fd92bffd40
