---
kubectl_force_update: false

#https://kubernetes.io/releases/
# renovate: datasource=github-releases depName=kubernetes/kubernetes versioning=semver
kubectl_ver: 'v1.35.0'

#https://dl.k8s.io/v1.34.1/kubernetes-client-linux-amd64.tar.gz
kubectl_download_url: 'https://dl.k8s.io/{{ kubectl_ver }}/kubernetes-client-linux-amd64.tar.gz'

kubectl_install_dir: '/usr/local/bin'

#https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.34.md#client-binaries
# renovate: datasource=github-releases depName=kubernetes/kubernetes packageName=kubernetes-client-linux-amd64.tar.gz
kubectl_checksum: sha512:3abedd362fffd5eb749febdeb59c2edd9902f7f69fb182f879daeb27cc88405983c539513cb74ef9b9587ab3829bde992f22f2067fd181311989345f6e13b867