---
# renovate: datasource=github-releases depName=cilium/cilium-cli versioning=semver
cilium_cli_ver: 'v0.18.9'

cilium_cli_install_dir: /usr/local/bin

cilium_cli_force_update: false

#https://github.com/cilium/cilium-cli/releases/tag/v0.18.9
#https://github.com/cilium/cilium-cli/releases/download/v0.18.9/cilium-linux-amd64.tar.gz
cilium_cli_download_url: 'https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_ver }}/cilium-linux-amd64.tar.gz'

#https://github.com/cilium/cilium-cli/releases/download/v0.18.9/cilium-linux-amd64.tar.gz.sha256sum
# renovate: datasource=github-releases depName=cilium/cilium-cli packageName=cilium-linux-amd64.tar.gz
cilium_cli_checksum: sha256:15978aaf82373b0682aa87ab217848b3fb6e3cd80adad365d34696fe92543923
