---
# renovate: datasource=github-releases depName=helm/helm versioning=semver
helm_ver: 'v3.19.2'

helm_install_dir: /usr/local/bin

helm_force_update: false

#https://github.com/helm/helm/tags
# https://get.helm.sh/helm-v3.19.2-linux-amd64.tar.gz
helm_download_url: 'https://get.helm.sh/helm-{{ helm_ver }}-linux-amd64.tar.gz'

# https://get.helm.sh/helm-v3.19.2-linux-amd64.tar.gz.sha256sum
# renovate: datasource=github-releases depName=helm/helm packageName=helm-v<semver>-linux-amd64.tar.gz
helm_checksum: sha256:2114c9dea2844dce6d0ee2d792a9aae846be8cf53d5b19dc2988b5a0e8fec26e
