---
# renovate: datasource=github-releases depName=gruntwork-io/terragrunt versioning=semver
terragrunt_version: 'v0.92.1'

os_arch: 'linux_amd64'

terragrunt_install_dir: /usr/local/bin

terragrunt_force_update: false

#https://github.com/gruntwork-io/terragrunt/releases/download/v0.89.0/terragrunt_linux_amd64
terragrunt_download_url: 'https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_version }}/terragrunt_{{ os_arch }}'

# https://github.com/gruntwork-io/terragrunt/releases/download/v0.89.0/SHA256SUMS
# renovate: datasource=github-releases depName=gruntwork-io/terragrunt packageName=terragrunt_linux_amd64
terragrunt_checksum: sha256:0fca48ca7f9b806800b97886894c275a4d780fac94a3a7358778664a86d3cde4
