---
# renovate: datasource=github-releases depName=gruntwork-io/terragrunt versioning=semver
terragrunt_version: 'v0.94.0'

os_arch: 'linux_amd64'

terragrunt_install_dir: /usr/local/bin

terragrunt_force_update: false

#https://github.com/gruntwork-io/terragrunt/releases/download/v0.93.10/terragrunt_linux_amd64
terragrunt_download_url: 'https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_version }}/terragrunt_{{ os_arch }}'

# https://github.com/gruntwork-io/terragrunt/releases/download/v0.93.10/SHA256SUMS
# renovate: datasource=github-releases depName=gruntwork-io/terragrunt packageName=terragrunt_linux_amd64
terragrunt_checksum: sha256:13cb467a8cd49ca38e8021a6141be7a9e743928ed6a5112e50c3a10bfc560535
