---
# renovate: datasource=github-releases depName=stackrox/kube-linter versioning=semver
kube_linter_version: 'v0.8.1'

kube_linter_install_dir: /usr/local/bin

kube_linter_force_update: false

# https://github.com/stackrox/kube-linter/releases/
kube_linter_download_url: 'https://github.com/stackrox/kube-linter/releases/download/{{ kube_linter_version }}/kube-linter-linux'

# renovate: datasource=github-releases depName=stackrox/kube-linter packageName=kube-linter-linux
kube_linter_checksum: sha256:cb36fae850360ddec21e81f577774c3bf9d13534c2e7f2ce50c5f695f6461dcf
